'QUAN_TRI_LOP_HOC'[
  'XEM_CHI_TIET_LOP_HOC'[
    ('LOP_HOC_THOI_KHOA_BIEU',
    'LOP_HOC_DANH_SACH_GIANG_VIEN',
    'LOP_HOC_DANH_SACH_SINH_VIEN',
    'LOP_HOC_DANH_SACH_DIEM_DANH')
  ]
];




'QUAN_TRI_VAN_BAN'[
    'QUAN_TRI_VAN_BAN_THAO_TAC',
]

'QUAN_TRI_THONG_BAO'[
    'QUAN_TRI_THONG_BAO_THAO_TAC',
]

'QUAN_TRI_KHAO_SAT'[
    'QUAN_TRI_KHAO_SAT_THAO_TAC',
]

'PHAN_HOI'[
    'HOI_DAP'[
        'HOI_DAP_SINH_VIEN',
        'HOI_DAP_GIANG_VIEN',
    ],
    'HO_TRO_KI_THUAT'
];

'IMPORT_DU_LIEU'[
  ('IMPORT_LOP_TIN_CHI', 'IMPORT_DANH_SACH_SINH_VIEN', 'IMPORT_DANH_SACH_GIANG_VIEN')
];

'CHUONG_TRINH_KHUNG'[
    'CHUONG_TRINH_KHUNG_THAO_TAC'
]

'THONG_TIN_KY_HOC'[
    'THONG_TIN_KY_HOC_GIANG_VIEN',
    'THONG_TIN_KY_HOC_SINH_VIEN',
];

'HOC_LIEU_SO'[
    'HOC_LIEU_SO_THAO_TAC'
]




